### ISSUE TITLE
Parsing Fails on request.body

### ISSUE THREAD

**Issue by mishawagon** [menan/SparkJson#1]
Thank you very much for this library. When I run your example, it works. But if instead of using a json string in the code, I load it using the HTTP client library, the parsing breaks. The http client is pulling down a page that has nothing on it but the same exact text as your example:

{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}

Any ideas why parseObject() would fail if the data is coming in as a request.body that has been copied over to a string?

void loop() {
    if (nextTime > millis()) {
        return;
    }

```
request.hostname = "misharabinovich.com";
request.path = "/projects/sprk/index.html";

request.port = 80;
```

  // Get request
    http.get(request, response, headers);

```
char charBuf[300];
response.body.toCharArray(charBuf, 300);

char json[] = {};
strcpy(json, charBuf);
StaticJsonBuffer<300> jsonBuffer;

JsonObject& root = jsonBuffer.parseObject(json);

nextTime = millis() + 10000;
Serial.print("Response Begin\t");
Serial.println(charBuf);
if (!root.success()) {

    Serial.println("parseObject() failed");
    return;
}

Serial.print("Response Begin\t");
long t_time = root["time"];
Serial.print(t_time);
```

}

**Comment by menan** [comment]
Check your JSON data to see if the size fits 300. I had to make it 2000 to get it working for my openweathermap data. To check how to find the right size for your data look at this original article from @bblanchon at [Memory Model - ArduinoJSON](https://github.com/bblanchon/ArduinoJson/wiki/Memory%20model)

Cheers

**Comment by mishawagon** [comment]
Hello thank you for your feedback. I tried 2000 and also the allocation method detailed in the linked article. The parse fails, however I am going through an extra step that also fails. I copy the body.response to a string first, because otherwise the char json[] = response.body fails with mismatched datatype error. The weird thing is that when I Serial.print the string that was created the first four characters are truncated:

ensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}

instead of:

{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}

I tried to quickly just add 4 spaces in the response file to "get rid" of this problem, but the parse still fails. Is your working code online anywhere by chance? I would love to use an existing api service that talks json http://sunrise-sunset.org/api

I am making a light that syncs to sun activity in a specific part of the world. Anyway, any info would be greatly appreciated!  Cheers

**Comment by mishawagon** [comment]
```
// This #include statement was automatically added by the Spark IDE.
#include "SparkJson/SparkJson.h"

// This #include statement was automatically added by the Spark IDE.
#include "HttpClient/HttpClient.h"

/**
* Declaring the variables.
*/
unsigned int nextTime = 0;    // Next time to contact the server
HttpClient http;

// Headers currently need to be set at init, useful for API keys etc.
http_header_t headers[] = {
    //  { "Content-Type", "application/json" },
    //  { "Accept" , "application/json" },
    { "Accept" , "*/*"},
    { NULL, NULL } // NOTE: Always terminate headers will NULL
};

http_request_t request;
http_response_t response;

void setup() {
    Serial.begin(9600);
}

void loop() {
    if (nextTime > millis()) {
        return;
    }
    request.hostname = "misharabinovich.com";
    request.path = "/projects/sprk/index.html";

    request.port = 80;

    http.get(request, response, headers);

    const int BUFFER_SIZE = JSON_OBJECT_SIZE(3) + JSON_ARRAY_SIZE(2);
    char charBuf[BUFFER_SIZE];
    response.body.toCharArray(charBuf, BUFFER_SIZE);

    char json[] = {};
    strcpy(json, charBuf);

    StaticJsonBuffer<BUFFER_SIZE> jsonBuffer;

    JsonObject& root = jsonBuffer.parseObject(json);

    nextTime = millis() + 10000;
    Serial.print("Converted to String\t");
    Serial.println(charBuf);
    if (!root.success()) {

        Serial.println("parseObject() failed");
        return;
    }

    Serial.print("Time is\t");
    long t_time = root["time"];
    Serial.print(t_time);

}
```

**Comment by menan** [comment]
I fried my Core by over powering it -_- I am waiting on a new one. When I get it, I'll test it out your code and get back to you.

**Comment by mishawagon** [comment]
Thank you very much for thinking about this! Sorry to hear the core is friend. Were you powering it via the power pin with an external power supply? Just curious.

For my part I was gonna look into the possibility that a newline is causing the difference, however now I can not get any Serial output. My usbserial is not showing up in the list of serial ports no matter how many times I restart my computer! I reinstalled FTDI drivers also, however that did not help. I'm gonna try to get that to work again and if you do have time to test the code I would gladly appreciate any thoughts from your end.

**Comment by mishawagon** [comment]
Hello,
Ok, I got my debugging setup working again. Here is the latest code, slightly tweaked for clarity. The goal here was to make the code totally the same as the example code and the parse works, which can be seen by commenting out the line:  strcpy(json, charBuf);

However, if that line is not commented out and the response.body is indeed copied to json variable, the parse fails. On the server, the newline has been deleted.

```
// This #include statement was automatically added by the Spark IDE.
#include "SparkJson/SparkJson.h"

// This #include statement was automatically added by the Spark IDE.
#include "HttpClient/HttpClient.h"

/**
* Declaring the variables.
*/
unsigned int nextTime = 0;    // Next time to contact the server
HttpClient http;

// Headers currently need to be set at init, useful for API keys etc.
http_header_t headers[] = {
    { "Content-Type", "application/json" },
    { "Accept" , "application/json" },
    { "Accept" , "*/*"},
    { NULL, NULL } // NOTE: Always terminate headers will NULL
};

http_request_t request;
http_response_t response;

void setup() {
    Serial.begin(9600);
}

void loop() {
    if (nextTime > millis()) {
        return;
    }

    request.hostname = "misharabinovich.com";
    request.path = "/projects/sprk/index.json";
    request.port = 80;

    http.get(request, response, headers);

    nextTime = millis() + 10000;

    const int BUFFER_SIZE = JSON_OBJECT_SIZE(3) + JSON_ARRAY_SIZE(2);
    char charBuf[BUFFER_SIZE];
    response.body.toCharArray(charBuf, BUFFER_SIZE);

    char json[] = "{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}";

    strcpy(json, charBuf);

    StaticJsonBuffer<200> jsonBuffer;
    JsonObject& root = jsonBuffer.parseObject(json);

    if (!root.success()) {
        Serial.println("parseObject() failed");
        return;
    }

    const char* sensor = root["sensor"];
    long time          = root["time"];
    double latitude    = root["data"][0];
    double longitude   = root["data"][1];

    Serial.print(time);
}
```

**Comment by menan** [comment]
what happens when you replace

```
const int BUFFER_SIZE = JSON_OBJECT_SIZE(3) + JSON_ARRAY_SIZE(2);
char charBuf[BUFFER_SIZE];
response.body.toCharArray(charBuf, BUFFER_SIZE);

char json[] = "{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}";

strcpy(json, charBuf);

StaticJsonBuffer<200> jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(json);

```

with

```
char *dataChar = (char*)response.body.c_str();
StaticJsonBuffer<2000> jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(dataChar);
```

? I made the buffer size  2000 just to be generous. You can lower it after if it works.

**Comment by mishawagon** [comment]
Sadly that generates the same results, though it is much cleaner code.

**Comment by bblanchon** [comment]
You inverted the arguments of `strcpy()`, it's destination first and then source:

```
strcpy(charBuf, json);
```

**Comment by mishawagon** [comment]
Bblanchon you are wrong, sorry. The line is meant to copy charBuf into json variable. Thanks for caring though!

**Comment by upuxaa** [comment]
Did anybody figure this out yet?

**Comment by mishawagon** [comment]
Not to my knowledge.

**Comment by bblanchon** [comment]
I confirm that the suggestion of @menan is correct:

```
char *dataChar = (char*)response.body.c_str();
StaticJsonBuffer<2000> jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(dataChar);
```

The code above should be working properly if the `response` is still in memory while you extract the JSON content from `root` 

By the way, if you upgrade to ArduinoJson 5.0, you can simplify it to:

```
StaticJsonBuffer<2000> jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(response.body);
```

There must be something wrong in your code.
Can you post the complete program?
Also please have a look at [ArduinoJson's wiki](https://github.com/bblanchon/ArduinoJson/wiki), and espicialy the [Avoiding Pitfalls](https://github.com/bblanchon/ArduinoJson/wiki/Avoiding%20pitfalls) section.

**Comment by mishawagon** [comment]
Hello thank you. I had already tried menan's suggestion, as well as pasted my complete code above. The only new thing I can see in your suggestion is to upgrade to ArduinoJson 5.0 and to see if that works. I will try that, however the Spark Core I had was borrowed and I already returned it. One day when I get my own I will try it out and follow up. Thanks.

**Comment by fowie** [comment]
Any progress on this?  I can get it to work for simple JSON like the example shown, but if the JSON includes nested objects, like results from openweathermap.org, parsing always fails?

**Comment by jhlink** [comment]
@menan Any plans to upgrade to ArduinoJson 5.0? If not, I can try my hand at it.

**Comment by jhlink** [comment]
@mishawagon I've explored this problem and tried a more vigorous test using food2fork's API. 

```
{"recipe": {
    "publisher": "Closet Cooking", 
    "f2f_url": "http://food2fork.com/view/35382", 
    "ingredients": ["2 jalapeno peppers, cut in half lengthwise and seeded", 
        "2 slices sour dough bread", 
        "1 tablespoon butter, room temperature", 
        "2 tablespoons cream cheese, room temperature", 
        "1/2 cup jack and cheddar cheese, shredded", 
        "1 tablespoon tortilla chips, crumbled\n"], 
    "source_url": "http://www.closetcooking.com/2011/04/jalapeno-popper-grilled-cheese-sandwich.html", 
    "recipe_id": "35382", 
    "image_url": "http://static.food2fork.com/Jalapeno2BPopper2BGrilled2BCheese2BSandwich2B12B500fd186186.jpg", 
    "social_rank": 100.0, 
    "publisher_url": "http://closetcooking.com", 
    "title": "Jalapeno Popper Grilled Cheese Sandwich"
    }
}
```

The above JSON is what I used to see if I can replicate the error. 

@bblanchon suggestion is correct. The SparkJson library works perfectly. The problem lies within the HttpClient library that you're using. I've read through the HttpClient library, and the main problem is that the **buffer size for the response.body** may not be big enough. (It's currently set at 1024 by default. I should probably put in a PR for that where a user can optionally change that buffer size that in that repo.)

The result is a malformed JSON object. (Missing curly brackets, objects, attributes, etc.)
This is why "ParseObject Failed" is returning. 

@fowie I'm pretty sure you might be dealing with the same problem. Try copying the entire HttpClient library, and changing the default buffer size in HttpClient.h from 1024 to some large number like 2048 or something. 

@menan , I believe this resolves/closes this issue. Also, do you think you can add me as a collab to the repo? :) I would like to help manage the SparkJson library as updates and issues come by.

**Comment by jhlink** [comment]
Even though I used a larger, somewhat more rigorous test case, I had this nagging feeling that my solution wasn't the solution that @mishawagon was looking for. 

It wasn't until that I looked at the raw HTTP Response Body that I realized it's neither the fault of the HttpClient library or the SparkJson library. 

```
{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}
```

@mishawagon , you have a faulty JSON object. The '\' characters makes the JSON object invalid. Even though you're able to correctly convert it from string to c_str(), when you put that raw JSON object into the JsonParser, an error is returned. 

Your JSON object should really look like this. 

```
{"sensor":"gps","time":1351824120,"data":[48.756080,2.302038]}
```

The following is the corrected code. I've made the additions that @menan and @bblanchon both had suggested, but in addition, I added a snippet that would removed the '\' character. Keep in mind it's limited to checking the exact length of the original JSON object above.

It would be best to fix this syntax error on the server side, and remove my addition to the code for best practices.

```
// This #include statement was automatically added by the Spark IDE.
#include "SparkJson/SparkJson.h"

// This #include statement was automatically added by the Spark IDE.
#include "HttpClient.h"

/**
* Declaring the variables.
*/
unsigned int nextTime = 0;    // Next time to contact the server
HttpClient http;

// Headers currently need to be set at init, useful for API keys etc.
http_header_t headers[] = {
    //  { "Content-Type", "application/json" },
    //  { "Accept" , "application/json" },
    { "Accept" , "*/*"},
    { NULL, NULL } // NOTE: Always terminate headers will NULL
};

http_request_t request;
http_response_t response;

void setup() {
    Serial.begin(9600);
}

void loop() {
    if (nextTime > millis()) {
        return;
    }
    request.hostname = "misharabinovich.com";
    request.path = "/projects/sprk/index.html";
    request.port = 80;

    http.get(request, response, headers);

    char *tempBuf = (char*)response.body.c_str();

            // The following code is my addition. Ideally, this should be removed once the server side
            // issue is fixed. 
            char charBuf[71];
    int val = 0;
    for (int i = 0; i < 71; ++i) {
        if (tempBuf[i] == '\\') {
            continue;
        }
        charBuf[val] =  tempBuf[i];
        val++;
    }



    StaticJsonBuffer<2000> jsonBuffer;
    JsonObject& root = jsonBuffer.parseObject(charBuf);
    root.printTo(Serial);
    // Serial.println(charBuf);
    nextTime = millis() + 1000;
    Serial.print("Converted to String\t");
    if (!root.success()) {

        Serial.println("parseObject() failed");
        return;
    }

    Serial.print("Time is\t");
    long t_time = root["time"];
    Serial.print(t_time);
}
```

This issue is now closed and resolved. :) 
Many thanks to @menan for adding me as collaborator and finally allowing me to put this issue to rest! :D
